<!doctype html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><link rel="icon" type="image/png" href="{{ asset('favicon.png') }}?v=2"><link rel="shortcut icon" type="image/png" href="{{ asset('favicon.png') }}?v=2"><link rel="apple-touch-icon" href="{{ asset('favicon.png') }}?v=2"><title>User Management · NMS Starcom</title>@vite(['resources/css/app.css','resources/js/users.js'])</head>
<body class="operations-app"><aside class="sidebar" aria-label="Primary navigation"><div class="brand starcom-brand"><img src="{{ asset('images/starcom-logo.png') }}" alt="Starcom"><div><strong>NMS STARCOM</strong><small>NETWORK MONITORING</small></div></div><nav><a class="nav-link nav-anchor" href="{{ route('dashboard') }}"><span>⌂</span> Dashboard</a><div class="nav-group"><button class="nav-link nav-parent" type="button" aria-expanded="false"><span>⌘</span> Topology <i>⌄</i></button><div class="nav-submenu"><a class="nav-link nav-child nav-anchor" href="{{ route('dashboard') }}#topology"><span>⌖</span> Map Monitoring</a></div></div><div class="nav-group"><button class="nav-link nav-parent" type="button" aria-expanded="false"><span>▦</span> Device Management <i>⌄</i></button><div class="nav-submenu"><a class="nav-link nav-child nav-anchor" href="{{ route('dashboard') }}#devices"><span>▤</span> Devices</a></div></div><a class="nav-link nav-anchor" href="{{ route('projects.index') }}"><span>▣</span> Project Management</a><a class="nav-link nav-anchor active" href="{{ route('users.index') }}"><span>♙</span> User Management <b>{{ $users->count() }}</b></a><a class="nav-link nav-anchor" href="{{ route('about') }}"><span>ⓘ</span> About</a></nav><div class="side-status"><i></i><div><small>ACCESS CONTROL</small><strong>Administrator</strong><span>Identity scope</span></div></div></aside>
<main><header class="app-header"><div><p class="eyebrow">SYSTEM / <span>USER MANAGEMENT</span></p><h1>Access &amp; roles</h1><p class="header-context">Control operator access and administrative privileges across the NMS.</p></div><div class="header-actions"><button class="theme-toggle" type="button" data-theme-toggle aria-pressed="false"><span data-theme-icon>☀</span><span data-theme-label>Light</span></button><a class="button ghost button-link" href="{{ route('dashboard') }}">← Dashboard</a><button class="button primary" id="addUser">＋ Add user</button></div></header>
@if(session('success'))<div class="toast">{{ session('success') }}</div>@endif @if($errors->any())<div class="toast error">{{ $errors->first() }}</div>@endif
<section class="user-stats"><article><small>TOTAL USERS</small><strong>{{ $users->count() }}</strong></article><article><small>ADMINISTRATORS</small><strong>{{ $users->where('role','administrator')->count() }}</strong></article><article><small>MONITORING USERS</small><strong>{{ $users->where('role','user')->count() }}</strong></article><article><small>ACTIVE</small><strong>{{ $users->where('is_active',true)->count() }}</strong></article></section>
<article class="panel devices-panel"><div class="section-head"><div><p class="eyebrow">ACCESS DIRECTORY</p><h2>Registered users</h2></div></div><div class="table-wrap"><table><thead><tr><th>User</th><th>Username</th><th>Role</th><th>Scope</th><th>Status</th><th>Last login</th><th></th></tr></thead><tbody>
@foreach($users as $user)<tr><td><div class="user-identity"><span>{{ strtoupper(substr($user->name,0,1)) }}</span><div><strong>{{ $user->name }}</strong><small>{{ $user->email ?: 'No email' }}</small></div></div></td><td><code>{{ $user->username }}</code></td><td><span class="role-badge {{ $user->role }}">{{ strtoupper($user->role) }}</span></td><td><small>{{ $user->isAdministrator() ? 'Devices + users · Full control' : 'Monitoring · Web · Telnet' }}</small></td><td><span class="status-pill {{ $user->is_active ? 'online':'offline' }}"><i></i>{{ $user->is_active ? 'ACTIVE':'DISABLED' }}</span></td><td>{{ $user->last_login_at?->diffForHumans() ?? 'Never' }}</td><td><div class="row-actions"><button class="icon-btn edit-user" data-user='@json($user)'>✎</button>@if(!auth()->user()->is($user))<form method="POST" action="{{ route('users.destroy',$user) }}" onsubmit="return confirm('Hapus user ini?')">@csrf @method('DELETE')<button class="icon-btn danger">×</button></form>@endif</div></td></tr>@endforeach
</tbody></table></div></article></main>
<dialog id="userModal"><form method="POST" id="userForm" action="{{ route('users.store') }}">@csrf<input type="hidden" name="_method" id="userMethod" value="POST"><div class="modal-head"><div><p class="eyebrow">ACCESS MANAGEMENT</p><h2 id="userModalTitle">Add user</h2></div><button type="button" class="close-user">×</button></div><div class="form-grid"><label class="span-2">Full name<input name="name" required></label><label>Username<input name="username" required></label><label>Email<input type="email" name="email"></label><label class="span-2">Role<select name="role"><option value="user">User — Monitoring & remote</option><option value="administrator">Administrator — Full control</option></select></label><label>Password<input type="password" name="password" id="userPassword"></label><label>Confirm password<input type="password" name="password_confirmation" id="userPasswordConfirmation"></label><label class="toggle span-2"><input type="checkbox" name="is_active" value="1" checked> Active account</label><p class="password-note span-2">Saat edit, kosongkan password jika tidak ingin mengubahnya.</p></div><div class="modal-actions"><button type="button" class="button ghost close-user">Cancel</button><button class="button primary">Save user</button></div></form></dialog>
</body></html>
