<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><link rel="icon" href="{{ asset('favicon.png') }}?v=2"><title>{{ $project->name }} Topology · NMS Starcom</title>@vite(['resources/css/app.css','resources/js/topology-detail.js','resources/js/region-toggle.js'])</head>
<body class="operations-app"><aside class="sidebar" aria-label="Primary navigation"><div class="brand starcom-brand"><img src="{{ asset('images/starcom-logo.png') }}" alt="Starcom"><div><strong>NMS STARCOM</strong><small>NETWORK MONITORING</small></div></div><nav><a class="nav-link nav-anchor" href="{{ route('dashboard') }}"><span>⌂</span> Dashboard</a><div class="nav-group"><button class="nav-link nav-parent" type="button" aria-expanded="true"><span>⌘</span> Topology <i>⌄</i></button><div class="nav-submenu"><a class="nav-link nav-child nav-anchor active" href="{{ route('dashboard') }}#topology"><span>⌖</span> Map Monitoring</a></div></div><div class="nav-group"><button class="nav-link nav-parent" type="button" aria-expanded="false"><span>▦</span> Device Management <i>⌄</i></button><div class="nav-submenu"><a class="nav-link nav-child nav-anchor" href="{{ route('dashboard') }}#devices"><span>▤</span> Devices</a></div></div>@if(auth()->user()->isAdministrator())<a class="nav-link nav-anchor" href="{{ route('projects.index') }}"><span>▣</span> Project Management</a><a class="nav-link nav-anchor" href="{{ route('users.index') }}"><span>♙</span> User Management</a>@endif<a class="nav-link nav-anchor" href="{{ route('about') }}"><span>ⓘ</span> About</a></nav><div class="side-status"><i></i><div><small>PROJECT NETWORK</small><strong>{{ $project->name }}</strong><span>Topology scope</span></div></div></aside>
<main><header class="app-header"><div><p class="eyebrow">TOPOLOGY / <span>{{ strtoupper($project->name) }}</span></p><h1>Region &amp; device topology</h1><p class="header-context">Network hierarchy, station relationships, and active fault state for this project.</p></div><div class="header-actions"><button class="theme-toggle" type="button" data-theme-toggle aria-pressed="false"><span data-theme-icon>☀</span><span data-theme-label>Light</span></button><button class="button ghost refresh-project-button" type="button">↻ Check this project</button><button class="button ghost" id="openTelemetryExport" type="button">Export SNMP Word</button><a class="button ghost button-link" href="{{ route('dashboard') }}#topology">← All projects</a></div></header>
<section class="project-location-panel"><div class="project-location-map"><img class="indonesia-map-art" src="{{ asset('assets/indonesia.svg') }}" alt="Indonesia"><span class="project-location-marker" style="left:{{ $mapLeft }}%;top:{{ $mapTop }}%"><i></i>{{ $project->location ?: 'Project location' }}</span></div><aside><p class="eyebrow">PROJECT LOCATION</p><h2>{{ $project->location ?: 'Indonesia' }}</h2><p>{{ $project->devices->count() }} managed devices · {{ $project->devices->where('status','online')->count() }} online · {{ $project->devices->where('status','offline')->count() }} offline</p><span>{{ $projectLatitude === null ? 'Province placement' : number_format($projectLatitude, 4).', '.number_format($projectLongitude, 4) }}</span></aside></section>
<article class="panel topology-panel project-detail-panel"><div class="section-head"><div><p class="eyebrow">PROJECT DETAIL · REGION MAP</p><h2>{{ $project->name }}</h2></div><div class="legend"><span><i class="online"></i>Online</span><span><i class="offline"></i>Offline</span><span><i class="unknown"></i>Unknown</span></div></div>
@php $typeStats=$project->devices->groupBy('type')->map(fn($items)=>['total'=>$items->count(),'online'=>$items->where('status','online')->count(),'offline'=>$items->where('status','offline')->count()]); @endphp
<div class="detail-topology"><div class="detail-project-node"><span>PROJECT</span><strong>{{ $project->name }}</strong><small>{{ $project->customer_name }} · {{ $project->devices->count() }} devices · {{ $project->location }}</small>@if($typeStats->isNotEmpty())<div class="project-type-stats"><div class="stats-head"><b>DEVICE TYPE</b><span>TOTAL</span><i>ON</i><i>OFF</i></div>@foreach($typeStats as $type=>$counts)<div><b>{{ $type }}</b><span title="Total">{{ $counts['total'] }}</span><i class="online" title="Online">{{ $counts['online'] }}</i><i class="offline" title="Offline">{{ $counts['offline'] }}</i></div>@endforeach</div>@endif<div class="project-sla-summary"><b>SLA PROJECT · LAST 30 DAYS</b><strong>{{ $projectSla === null ? 'SLA OFF' : number_format($projectSla, 2).'%' }}</strong></div></div><div class="detail-trunk"></div>
@if($project->devices->isEmpty())<div class="empty-project-node">No devices assigned to this project</div>@else<div class="detail-regions">
@foreach($project->devices->groupBy('region') as $region=>$devices)
@php
    $onlineCount = $devices->where('status','online')->count();
    $offlineCount = $devices->where('status','offline')->count();
    $baseStationIds = $devices->where('station_role', 'BS')->pluck('id');
    $rootDevices = $devices->filter(fn($device) => $device->station_role !== 'SS' || !$device->parent_id || !$baseStationIds->contains($device->parent_id));
@endphp
<section class="detail-region"><div class="detail-region-line"></div><button type="button" class="region-node region-toggle" aria-expanded="true" title="Klik untuk tampilkan atau sembunyikan Base Station"><span>{{ $region }}</span><strong>{{ $devices->first()->city }}</strong><small class="region-summary"><i>{{ $devices->count() }} TOTAL</i><i class="online">{{ $onlineCount }} ON</i><i class="offline">{{ $offlineCount }} DOWN</i></small></button><div class="detail-devices">
@foreach($rootDevices as $device)
    @if($device->station_role === 'BS')
        @php $subscribers = $devices->where('parent_id', $device->id); @endphp
        <section class="station-tree collapsed"><button type="button" class="base-station-toggle {{ $device->status }}" aria-expanded="false"><b>BS</b><span>{{ $device->name }}</span><small>{{ $device->sector ?: 'Tanpa sektor' }} · {{ $device->ip_address }} · {{ strtoupper($device->status) }} <mark>{{ $device->sla_enabled ? 'SLA '.number_format($device->sla_percentage, 2).'%' : 'SLA OFF' }}</mark></small><em>{{ $subscribers->count() }} SS</em></button><div class="subscriber-list"><div class="station-remote"><span>BS ACCESS</span>@include('topology.device-button',['device'=>$device])</div>@forelse($subscribers as $subscriber)<div class="subscriber-item"><span>SS</span>@include('topology.device-button',['device'=>$subscriber])</div>@empty<div class="empty-subscribers">Belum ada Subscriber Station terhubung</div>@endforelse</div></section>
    @elseif($device->station_role === 'SS')
        <div class="orphan-subscriber"><span>SS · BELUM TERHUBUNG BS</span>@include('topology.device-button',['device'=>$device])</div>
    @else
        @include('topology.device-button',['device'=>$device])
    @endif
@endforeach
</div></section>@endforeach</div>@endif</div></article></main>
<dialog id="detailRemote" class="remote-modal"><div class="modal-head"><div><p class="eyebrow">REMOTE ACCESS</p><h2 id="detailRemoteName">Device</h2></div><button class="close-detail">×</button></div><div class="remote-device-summary"><span class="remote-device-icon" id="detailIcon">■</span><div><strong id="detailIp"></strong><small id="detailType"></small></div></div><div class="remote-options"><a id="detailWeb" class="remote-option web" target="_blank"><span>↗</span><div><strong>Web Management</strong><small>Open in new tab</small></div></a><a id="detailTelnet" class="remote-option telnet"><span>⌁</span><div><strong>Telnet</strong><small>Open terminal connection</small></div></a><a id="detailSsh" class="remote-option ssh"><span>&gt;_</span><div><strong>SSH</strong><small>Open secure terminal</small></div></a><button id="detailSnmp" class="remote-option snmp" type="button"><span>⌁</span><div><strong>SNMP Graph</strong><small id="detailSnmpHelp">Tampilkan grafik garis berdasarkan OID</small></div><b id="detailSnmpPort">UDP/161</b></button><button id="detailCopy" class="remote-option copy"><span>⧉</span><div><strong>Copy IP address</strong><small>Copy to clipboard</small></div></button></div></dialog>
<dialog id="detailGraph" class="graph-modal"><div class="modal-head"><div><p class="eyebrow" id="detailGraphProtocol">SNMP TELEMETRY</p><h2 id="detailGraphTitle">SNMP graph</h2></div><button class="close-detail-graph">×</button></div><div class="graph-toolbar"><select id="detailOidSelect"></select><select id="detailPeriodSelect"><option value="1">Last 1 hour</option><option value="6">Last 6 hours</option><option value="24" selected>Last 24 hours</option><option value="168">Last 7 days</option><option value="720">Last 30 days</option><option value="8760">Last 1 year</option><option value="custom">Custom date</option></select><button class="button ghost" id="detailPollSnmp">↻ Poll now</button></div><div class="custom-date-range" id="detailCustomRange" hidden><label>Start date<input type="datetime-local" id="detailStartDate"></label><label>End date<input type="datetime-local" id="detailEndDate"></label></div><div class="chart-wrap"><canvas id="detailSnmpChart" width="900" height="360"></canvas><div id="detailChartEmpty">Pilih sensor dan periode, lalu klik Poll now.</div></div><div class="graph-footer"><span id="detailGraphStatus"></span><span id="detailGraphRange"></span><span id="detailGraphLatest"></span></div></dialog>
@php $exportSensors=$project->devices->flatMap(fn($device)=>collect($device->snmp_oids??[]))->filter(fn($sensor)=>!empty($sensor['oid']))->unique('oid')->values(); @endphp
<dialog id="telemetryExportDialog" class="export-modal"><form method="POST" action="{{ route('projects.telemetry.export',$project) }}">@csrf<div class="modal-head"><div><p class="eyebrow">{{ strtoupper($project->name) }}</p><h2>Export SNMP ke Word</h2></div><button type="button" id="closeTelemetryExport">×</button></div><div class="export-grid"><fieldset><legend>Pilih site</legend><label class="select-all"><input type="checkbox" data-check-all="site"> Pilih semua site</label><div class="export-list">@foreach($project->devices as $device)<label><input type="checkbox" class="export-site" name="device_ids[]" value="{{ $device->id }}"><span>{{ $device->name }}</span><small>{{ $device->ip_address }}</small></label>@endforeach</div></fieldset><fieldset><legend>Pilih sensor</legend><label class="select-all"><input type="checkbox" data-check-all="sensor"> Pilih semua sensor</label><div class="export-list">@foreach($exportSensors as $sensor)<label><input type="checkbox" class="export-sensor" name="oids[]" value="{{ $sensor['oid'] }}"><span>{{ $sensor['label']??$sensor['oid'] }}</span><small>{{ $sensor['oid'] }}</small></label>@endforeach</div></fieldset></div><label class="export-period">Periode<select name="period" id="exportPeriod"><option value="1">Last 1 hour</option><option value="6">Last 6 hours</option><option value="24">Last 24 hours</option><option value="168" selected>Last 7 days</option><option value="720">Last 30 days</option><option value="8760">Last 1 year</option><option value="custom">Custom date</option></select></label><div class="custom-date-range" id="exportCustomRange" hidden><label>Start date<input type="datetime-local" class="date-picker-priority" name="start_date"></label><label>End date<input type="datetime-local" class="date-picker-priority" name="end_date"></label></div><div class="modal-actions"><button class="button primary" type="submit">Download DOCX</button></div></form></dialog></body></html>
