[program:starnms-worker]
directory=/var/www/starnms
command=php artisan queue:work redis --queue=monitoring,default --sleep=1 --tries=2 --timeout=25 --max-time=3600
process_name=%(program_name)s_%(process_num)02d
numprocs=8
autostart=true
autorestart=true
stopwaitsecs=30
redirect_stderr=true
stdout_logfile=/var/log/supervisor/starnms-worker.log
